# Generated by Django 4.2.5 on 2023-09-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaible',
            new_name='available',
        ),
    ]
