# Generated by Django 4.2.5 on 2023-09-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_rename_avaible_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
    ]
